# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/peridot/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),peridot)

$(call add-radio-file-sha1-checked,radio/abl.img,23297d0e2e45c7097ad2508b9128efc8291d950b)
$(call add-radio-file-sha1-checked,radio/aop.img,1bd0e6e6bc784274749160869d1c50b31be120d3)
$(call add-radio-file-sha1-checked,radio/aop_config.img,75dcd828011a6f021cf2b406feca48c2af1eb9f5)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,4f468b015e04e926fe68adc4a29609c368fc2da2)
$(call add-radio-file-sha1-checked,radio/cpucp.img,19c2cf75b01f4a0cfdd4e6fe95bc0ac79c143a72)
$(call add-radio-file-sha1-checked,radio/cpucp_dtb.img,266aa9254df636102521c84aaa1ddd4d354bbb40)
$(call add-radio-file-sha1-checked,radio/devcfg.img,a4829a2c50bc9e2f25c53f14dd41476ca0f2c92e)
$(call add-radio-file-sha1-checked,radio/dsp.img,e1264ddc0aa39e54ddcf996ba0cb582abc66162f)
$(call add-radio-file-sha1-checked,radio/featenabler.img,ec73c94b717abda8b7b0ac81b9fac1e8dc84741b)
$(call add-radio-file-sha1-checked,radio/hyp.img,13ecdfe374839c7dca3a2c7b2e4e578a213516dc)
$(call add-radio-file-sha1-checked,radio/imagefv.img,3879b48fe0f33bae5fd200e3fdfa54ed5a1faec0)
$(call add-radio-file-sha1-checked,radio/keymaster.img,31f65fb9c792cf8435c65fcaf85dc28bd6a3ba69)
$(call add-radio-file-sha1-checked,radio/modem.img,59b8eac57cc8489b9d4dd7f7b621c53de4bb9ddc)
$(call add-radio-file-sha1-checked,radio/modemfirmware.img,f03baf47965b6af4036a6e6204f8f51937176cbc)
$(call add-radio-file-sha1-checked,radio/multiimgqti.img,85c6e03d0dd54630f5017c9c83517fbe19ad6af1)
$(call add-radio-file-sha1-checked,radio/qupfw.img,12b446d4145bc8a12c422b5db759e7d1727117d1)
$(call add-radio-file-sha1-checked,radio/shrm.img,c10b00923de371c30245d42b5523f464c6f5aee8)
$(call add-radio-file-sha1-checked,radio/tz.img,2b0e0ddee4356643d07c2b8d177498056a2552ac)
$(call add-radio-file-sha1-checked,radio/uefi.img,718fcce9a7066c0af4373cb9dfd297008a253356)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,ac0a3a76cad4cb7e485d4ee185bb520b8decd15a)
$(call add-radio-file-sha1-checked,radio/xbl.img,a9c0d593bd1b1b82ea3529ef157d15993e182120)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,dd177707c0cf98a1040f98b40beaf5264c1d29bd)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,1bf6be5329c771a6574789b7c9c207d9b5a125b3)

endif
